// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repository

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type ScudoRefreshToken struct {
	ID          int32
	UserID      uuid.UUID
	HashedToken string
	ExpiresAt   time.Time
	Revoked     bool
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type ScudoUser struct {
	ID             uuid.UUID
	Email          string
	HashedPassword string
	Metadata       json.RawMessage
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
