// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package repository

import (
	"context"
)

const createUser = `-- name: CreateUser :one
insert into scudo.users (email, hashed_password)
values ($1, $2)
returning id, email, hashed_password, created_at, updated_at
`

type CreateUserParams struct {
	Email          string
	HashedPassword string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (ScudoUser, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPassword)
	var i ScudoUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, hashed_password, created_at, updated_at from scudo.users where email = $1 limit 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (ScudoUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i ScudoUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userWithEmailExists = `-- name: UserWithEmailExists :one
select exists (select 1 from scudo.users where email = $1)
`

func (q *Queries) UserWithEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userWithEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
