// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package repository

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const createRefreshToken = `-- name: CreateRefreshToken :exec
insert into scudo.refresh_tokens (user_id, hashed_token, expires_at)
values ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	UserID      uuid.UUID
	HashedToken string
	ExpiresAt   time.Time
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.ExecContext(ctx, createRefreshToken, arg.UserID, arg.HashedToken, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
insert into scudo.users (email, hashed_password, metadata)
values ($1, $2, $3)
returning id, email, hashed_password, metadata, created_at, updated_at
`

type CreateUserParams struct {
	Email          string
	HashedPassword string
	Metadata       json.RawMessage
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (ScudoUser, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Email, arg.HashedPassword, arg.Metadata)
	var i ScudoUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
select id, email, hashed_password, metadata, created_at, updated_at from scudo.users where email = $1 limit 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (ScudoUser, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i ScudoUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.HashedPassword,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const userWithEmailExists = `-- name: UserWithEmailExists :one
select exists (select 1 from scudo.users where email = $1)
`

func (q *Queries) UserWithEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, userWithEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
